#!/usr/bin/env python3
"""
Simple test client for HTML-to-PDF Lambda function

Usage:
    FUNCTION_URL=https://your-url.lambda-url.eu-west-1.on.aws/ python test-client.py
"""

import os
import sys
import json
import base64
import time
from datetime import datetime
import requests

FUNCTION_URL = os.environ.get('FUNCTION_URL', 'https://your-url.lambda-url.eu-west-1.on.aws/')

# Sample HTML
SAMPLE_HTML = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Invoice</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            padding: 40px;
            color: #333;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        .invoice-info {{
            margin: 20px 0;
            padding: 15px;
            background-color: #ecf0f1;
            border-radius: 5px;
        }}
        .invoice-info p {{
            margin: 5px 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        table th {{
            background-color: #34495e;
            color: white;
            padding: 10px;
            text-align: left;
        }}
        table td {{
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }}
        .total {{
            text-align: right;
            font-size: 18pt;
            font-weight: bold;
            margin-top: 20px;
            color: #e74c3c;
        }}
    </style>
</head>
<body>
    <h1>Test Invoice #T001/2024</h1>

    <div class="invoice-info">
        <p><strong>Date:</strong> {datetime.now().strftime('%d/%m/%Y')}</p>
        <p><strong>Customer:</strong> Test Company S.r.l.</p>
        <p><strong>VAT:</strong> IT12345678901</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>IT Consulting Services</td>
                <td>10 hours</td>
                <td>€100.00</td>
                <td>€1,000.00</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Software License</td>
                <td>1</td>
                <td>€500.00</td>
                <td>€500.00</td>
            </tr>
        </tbody>
    </table>

    <div class="total">
        Total: €1,500.00
    </div>

    <p style="margin-top: 40px; font-size: 9pt; color: #7f8c8d; text-align: center;">
        Generated by HTML-to-PDF Lambda - {datetime.now().isoformat()}
    </p>
</body>
</html>"""


def test_pdf_generation():
    """Test PDF generation via Lambda function"""
    print('HTML-to-PDF Lambda Test Client')
    print('================================\n')
    print(f'Function URL: {FUNCTION_URL}\n')

    request = {
        'html': SAMPLE_HTML,
        'options': {
            'format': 'A4',
            'margin': {
                'top': '20mm',
                'right': '15mm',
                'bottom': '20mm',
                'left': '15mm'
            },
            'printBackground': True,
            'landscape': False
        },
        'outputFormat': 'base64'
    }

    print('Request details:')
    print(f"  HTML length: {len(request['html'])} bytes")
    print(f"  Format: {request['options']['format']}")
    print(f"  Output: {request['outputFormat']}\n")

    try:
        start_time = time.time()

        response = requests.post(
            FUNCTION_URL,
            json=request,
            headers={'Content-Type': 'application/json'},
            timeout=60
        )

        duration = time.time() - start_time

        print(f'Response received ({duration:.3f}s):')
        print(f'  Status: {response.status_code}')
        print(f'  Headers: {dict(response.headers)}\n')

        data = response.json()

        if data.get('success'):
            print('✅ PDF generated successfully!')
            print(f"  Size: {data['size']} bytes ({data['size'] / 1024:.2f} KB)")
            print(f"  Generation time: {data['generationTime']:.3f} seconds")
            print(f"  Total time: {duration:.3f} seconds")

            if 'pdfBase64' in data:
                # Save PDF to file
                pdf_bytes = base64.b64decode(data['pdfBase64'])
                output_path = 'test-output.pdf'
                with open(output_path, 'wb') as f:
                    f.write(pdf_bytes)
                print(f'\n📄 PDF saved to: {output_path}')
                print(f'   Open it with: open {output_path}')

            return True

        else:
            print('❌ PDF generation failed!')
            print(f"  Error: {data.get('error')}")
            print(f"  Message: {data.get('message')}")
            if 'details' in data:
                print(f"  Details: {data['details']}")
            return False

    except requests.exceptions.Timeout:
        print('❌ Request timed out!')
        return False
    except requests.exceptions.RequestException as e:
        print(f'❌ Request failed: {e}')
        return False
    except json.JSONDecodeError as e:
        print(f'❌ Failed to parse response: {e}')
        print(f'   Response: {response.text[:500]}...')
        return False
    except Exception as e:
        print(f'❌ Unexpected error: {e}')
        return False


if __name__ == '__main__':
    success = test_pdf_generation()
    print('\n' + ('✅ Test completed successfully!' if success else '❌ Test failed!') + '\n')
    sys.exit(0 if success else 1)
