export const SALE_STATUSES = [
  { value: 'proforma', label: 'Proforma' },
  { value: 'sent', label: 'Sent' },
  { value: 'paid', label: 'Paid' },
  { value: 'cancelled', label: 'Cancelled' },
]

export const PAYMENT_METHODS = [
  { value: 'bonifico', label: 'Bank Transfer' },
  { value: 'contanti', label: 'Cash' },
  { value: 'assegno', label: 'Check' },
  { value: 'carta', label: 'Credit Card' },
  { value: 'riba', label: 'Ri.Ba.' },
  { value: 'altro', label: 'Other' },
]

export const PAYMENT_TERMS = [
  { value: 'immediato', label: 'Immediate' },
  { value: '30gg', label: '30 days' },
  { value: '60gg', label: '60 days' },
  { value: '90gg', label: '90 days' },
  { value: '30-60gg', label: '30/60 days' },
  { value: '30-60-90gg', label: '30/60/90 days' },
]

export const TAX_RATES = [
  { value: 22, label: '22% (Standard)' },
  { value: 10, label: '10% (Reduced)' },
  { value: 5, label: '5% (Super reduced)' },
  { value: 4, label: '4% (Minimum)' },
  { value: 0, label: '0% (Exempt)' },
]

export const UNITS_OF_MEASURE = [
  { value: 'pz', label: 'Pieces (pz)' },
  { value: 'kg', label: 'Kilograms (kg)' },
  { value: 'lt', label: 'Liters (lt)' },
  { value: 'm', label: 'Meters (m)' },
  { value: 'mq', label: 'Square meters (mq)' },
  { value: 'mc', label: 'Cubic meters (mc)' },
  { value: 'ore', label: 'Hours' },
  { value: 'gg', label: 'Days' },
]

export const ITALIAN_PROVINCES = [
  { value: 'AG', label: 'Agrigento (AG)' },
  { value: 'AL', label: 'Alessandria (AL)' },
  { value: 'AN', label: 'Ancona (AN)' },
  { value: 'AO', label: 'Aosta (AO)' },
  { value: 'AP', label: 'Ascoli Piceno (AP)' },
  { value: 'AQ', label: "L'Aquila (AQ)" },
  { value: 'AR', label: 'Arezzo (AR)' },
  { value: 'AT', label: 'Asti (AT)' },
  { value: 'AV', label: 'Avellino (AV)' },
  { value: 'BA', label: 'Bari (BA)' },
  { value: 'BG', label: 'Bergamo (BG)' },
  { value: 'BI', label: 'Biella (BI)' },
  { value: 'BL', label: 'Belluno (BL)' },
  { value: 'BN', label: 'Benevento (BN)' },
  { value: 'BO', label: 'Bologna (BO)' },
  { value: 'BR', label: 'Brindisi (BR)' },
  { value: 'BS', label: 'Brescia (BS)' },
  { value: 'BT', label: 'Barletta-Andria-Trani (BT)' },
  { value: 'BZ', label: 'Bolzano (BZ)' },
  { value: 'CA', label: 'Cagliari (CA)' },
  { value: 'CB', label: 'Campobasso (CB)' },
  { value: 'CE', label: 'Caserta (CE)' },
  { value: 'CH', label: 'Chieti (CH)' },
  { value: 'CL', label: 'Caltanissetta (CL)' },
  { value: 'CN', label: 'Cuneo (CN)' },
  { value: 'CO', label: 'Como (CO)' },
  { value: 'CR', label: 'Cremona (CR)' },
  { value: 'CS', label: 'Cosenza (CS)' },
  { value: 'CT', label: 'Catania (CT)' },
  { value: 'CZ', label: 'Catanzaro (CZ)' },
  { value: 'EN', label: 'Enna (EN)' },
  { value: 'FC', label: 'Forl\u00ec-Cesena (FC)' },
  { value: 'FE', label: 'Ferrara (FE)' },
  { value: 'FG', label: 'Foggia (FG)' },
  { value: 'FI', label: 'Firenze (FI)' },
  { value: 'FM', label: 'Fermo (FM)' },
  { value: 'FR', label: 'Frosinone (FR)' },
  { value: 'GE', label: 'Genova (GE)' },
  { value: 'GO', label: 'Gorizia (GO)' },
  { value: 'GR', label: 'Grosseto (GR)' },
  { value: 'IM', label: 'Imperia (IM)' },
  { value: 'IS', label: 'Isernia (IS)' },
  { value: 'KR', label: 'Crotone (KR)' },
  { value: 'LC', label: 'Lecco (LC)' },
  { value: 'LE', label: 'Lecce (LE)' },
  { value: 'LI', label: 'Livorno (LI)' },
  { value: 'LO', label: 'Lodi (LO)' },
  { value: 'LT', label: 'Latina (LT)' },
  { value: 'LU', label: 'Lucca (LU)' },
  { value: 'MB', label: 'Monza e Brianza (MB)' },
  { value: 'MC', label: 'Macerata (MC)' },
  { value: 'ME', label: 'Messina (ME)' },
  { value: 'MI', label: 'Milano (MI)' },
  { value: 'MN', label: 'Mantova (MN)' },
  { value: 'MO', label: 'Modena (MO)' },
  { value: 'MS', label: 'Massa-Carrara (MS)' },
  { value: 'MT', label: 'Matera (MT)' },
  { value: 'NA', label: 'Napoli (NA)' },
  { value: 'NO', label: 'Novara (NO)' },
  { value: 'NU', label: 'Nuoro (NU)' },
  { value: 'OG', label: 'Ogliastra (OG)' },
  { value: 'OR', label: 'Oristano (OR)' },
  { value: 'OT', label: 'Olbia-Tempio (OT)' },
  { value: 'PA', label: 'Palermo (PA)' },
  { value: 'PC', label: 'Piacenza (PC)' },
  { value: 'PD', label: 'Padova (PD)' },
  { value: 'PE', label: 'Pescara (PE)' },
  { value: 'PG', label: 'Perugia (PG)' },
  { value: 'PI', label: 'Pisa (PI)' },
  { value: 'PN', label: 'Pordenone (PN)' },
  { value: 'PO', label: 'Prato (PO)' },
  { value: 'PR', label: 'Parma (PR)' },
  { value: 'PT', label: 'Pistoia (PT)' },
  { value: 'PU', label: 'Pesaro e Urbino (PU)' },
  { value: 'PV', label: 'Pavia (PV)' },
  { value: 'PZ', label: 'Potenza (PZ)' },
  { value: 'RA', label: 'Ravenna (RA)' },
  { value: 'RC', label: 'Reggio Calabria (RC)' },
  { value: 'RE', label: "Reggio Emilia (RE)" },
  { value: 'RG', label: 'Ragusa (RG)' },
  { value: 'RI', label: 'Rieti (RI)' },
  { value: 'RM', label: 'Roma (RM)' },
  { value: 'RN', label: 'Rimini (RN)' },
  { value: 'RO', label: 'Rovigo (RO)' },
  { value: 'SA', label: 'Salerno (SA)' },
  { value: 'SI', label: 'Siena (SI)' },
  { value: 'SO', label: 'Sondrio (SO)' },
  { value: 'SP', label: 'La Spezia (SP)' },
  { value: 'SR', label: 'Siracusa (SR)' },
  { value: 'SS', label: 'Sassari (SS)' },
  { value: 'SU', label: 'Sud Sardegna (SU)' },
  { value: 'SV', label: 'Savona (SV)' },
  { value: 'TA', label: 'Taranto (TA)' },
  { value: 'TE', label: 'Teramo (TE)' },
  { value: 'TN', label: 'Trento (TN)' },
  { value: 'TO', label: 'Torino (TO)' },
  { value: 'TP', label: 'Trapani (TP)' },
  { value: 'TR', label: 'Terni (TR)' },
  { value: 'TS', label: 'Trieste (TS)' },
  { value: 'TV', label: 'Treviso (TV)' },
  { value: 'UD', label: 'Udine (UD)' },
  { value: 'VA', label: 'Varese (VA)' },
  { value: 'VB', label: 'Verbano-Cusio-Ossola (VB)' },
  { value: 'VC', label: 'Vercelli (VC)' },
  { value: 'VE', label: 'Venezia (VE)' },
  { value: 'VI', label: 'Vicenza (VI)' },
  { value: 'VR', label: 'Verona (VR)' },
  { value: 'VS', label: 'Medio Campidano (VS)' },
  { value: 'VT', label: 'Viterbo (VT)' },
  { value: 'VV', label: 'Vibo Valentia (VV)' },
]

const ALPHA3_TO_2: Record<string, string> = {
  ALB: 'AL', AND: 'AD', AUT: 'AT', BEL: 'BE', BGR: 'BG',
  BIH: 'BA', BYR: 'BY', CAN: 'CA', CHE: 'CL', CHN: 'CN',
  CYP: 'CY', CZE: 'CZ', DEU: 'DE', DNK: 'DK', DZA: 'DZ',
  ESP: 'ES', EST: 'EE', FIN: 'FI', FRA: 'FR', GBR: 'GB',
  GRC: 'GR', KOR: 'KR', HRV: 'HR', HUN: 'HU', IRN: 'IR',
  IND: 'IN', IRL: 'IE', ISK: 'IS', ITA: 'IT', LIE: 'LI',
  LTU: 'LT', LUX: 'LU', LVL: 'LV', MEX: 'MX', MDL: 'MD',
  MKD: 'MK', MLT: 'MT', MNE: 'ME', NLD: 'NL', NOR: 'NO',
  POL: 'PL', PRT: 'PT', ROU: 'RO', SRB: 'RS', SVK: 'SK',
  SVN: 'SI', SWE: 'SE', SWZ: 'CH', TUR: 'TR', UKR: 'UA',
  RUS: 'RU', USA: 'US',
}

export function toAlpha2(code: string): string {
  if (!code) return ''
  const upper = code.toUpperCase()
  if (upper.length === 2) return upper
  return ALPHA3_TO_2[upper] || upper.slice(0, 2)
}

export const SECTORS = [
  { value: 'construction', label: 'Construction' },
  { value: 'mining', label: 'Mining' },
  { value: 'oil_gas', label: 'Oil & Gas' },
  { value: 'energy', label: 'Energy' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'food_beverage', label: 'Food & Beverage' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'chemicals', label: 'Chemicals' },
  { value: 'pharmaceuticals', label: 'Pharmaceuticals' },
  { value: 'technology', label: 'Technology' },
  { value: 'transport', label: 'Transport' },
  { value: 'other', label: 'Other' },
]

export const QUANTITY_OPTIONS = [
  { value: 'any', label: 'Any' },
  { value: 'small', label: 'Small batches' },
  { value: 'medium', label: 'Medium batches' },
  { value: 'large', label: 'Large batches' },
]

export const VAT_EXEMPT_OPTIONS = [
  { value: 'standard', label: 'Standard VAT' },
  { value: 'split_payment', label: 'Split Payment' },
  { value: 'exempt', label: 'VAT Exempt' },
]

export const CURRENCIES = [
  { value: 'EUR', label: 'EUR - Euro' },
  { value: 'USD', label: 'USD - US Dollar' },
  { value: 'GBP', label: 'GBP - British Pound' },
  { value: 'CHF', label: 'CHF - Swiss Franc' },
  { value: 'DZD', label: 'DZD - Algerian Dinar' },
  { value: 'EGP', label: 'EGP - Egyptian Pound' },
  { value: 'MAD', label: 'MAD - Moroccan Dirham' },
  { value: 'TND', label: 'TND - Tunisian Dinar' },
  { value: 'LYD', label: 'LYD - Libyan Dinar' },
  { value: 'SAR', label: 'SAR - Saudi Riyal' },
  { value: 'AED', label: 'AED - UAE Dirham' },
  { value: 'QAR', label: 'QAR - Qatari Riyal' },
  { value: 'KWD', label: 'KWD - Kuwaiti Dinar' },
  { value: 'TRY', label: 'TRY - Turkish Lira' },
  { value: 'CNY', label: 'CNY - Chinese Yuan' },
  { value: 'INR', label: 'INR - Indian Rupee' },
  { value: 'RUB', label: 'RUB - Russian Ruble' },
  { value: 'BRL', label: 'BRL - Brazilian Real' },
  { value: 'MXN', label: 'MXN - Mexican Peso' },
]

export const COUNTRIES = [
  { value: 'IT', label: 'Italy', flag: 'circle-flags:it', eu: true },
  { value: 'DE', label: 'Germany', flag: 'circle-flags:de', eu: true },
  { value: 'FR', label: 'France', flag: 'circle-flags:fr', eu: true },
  { value: 'AT', label: 'Austria', flag: 'circle-flags:at', eu: true },
  { value: 'CH', label: 'Switzerland', flag: 'circle-flags:ch', eu: false },
  { value: 'SI', label: 'Slovenia', flag: 'circle-flags:si', eu: true },
  { value: 'GB', label: 'United Kingdom', flag: 'circle-flags:gb', eu: false },
  { value: 'ES', label: 'Spain', flag: 'circle-flags:es', eu: true },
  { value: 'NL', label: 'Netherlands', flag: 'circle-flags:nl', eu: true },
  { value: 'BE', label: 'Belgium', flag: 'circle-flags:be', eu: true },
  { value: 'PL', label: 'Poland', flag: 'circle-flags:pl', eu: true },
  { value: 'CZ', label: 'Czech Republic', flag: 'circle-flags:cz', eu: true },
  { value: 'HR', label: 'Croatia', flag: 'circle-flags:hr', eu: true },
  { value: 'RO', label: 'Romania', flag: 'circle-flags:ro', eu: true },
  { value: 'PT', label: 'Portugal', flag: 'circle-flags:pt', eu: true },
  { value: 'SE', label: 'Sweden', flag: 'circle-flags:se', eu: true },
  { value: 'DK', label: 'Denmark', flag: 'circle-flags:dk', eu: true },
  { value: 'GR', label: 'Greece', flag: 'circle-flags:gr', eu: true },
  { value: 'HU', label: 'Hungary', flag: 'circle-flags:hu', eu: true },
  { value: 'IE', label: 'Ireland', flag: 'circle-flags:ie', eu: true },
  { value: 'SK', label: 'Slovakia', flag: 'circle-flags:sk', eu: true },
  { value: 'BG', label: 'Bulgaria', flag: 'circle-flags:bg', eu: true },
  { value: 'US', label: 'United States', flag: 'circle-flags:us', eu: false },
  { value: 'CA', label: 'Canada', flag: 'circle-flags:ca', eu: false },
  { value: 'TR', label: 'Turkey', flag: 'circle-flags:tr', eu: false },
  { value: 'DZ', label: 'Algeria', flag: 'circle-flags:dz', eu: false },
  { value: 'EG', label: 'Egypt', flag: 'circle-flags:eg', eu: false },
  { value: 'MA', label: 'Morocco', flag: 'circle-flags:ma', eu: false },
  { value: 'TN', label: 'Tunisia', flag: 'circle-flags:tn', eu: false },
  { value: 'LY', label: 'Libya', flag: 'circle-flags:ly', eu: false },
  { value: 'SA', label: 'Saudi Arabia', flag: 'circle-flags:sa', eu: false },
  { value: 'AE', label: 'United Arab Emirates', flag: 'circle-flags:ae', eu: false },
  { value: 'QA', label: 'Qatar', flag: 'circle-flags:qa', eu: false },
  { value: 'KW', label: 'Kuwait', flag: 'circle-flags:kw', eu: false },
  { value: 'CN', label: 'China', flag: 'circle-flags:cn', eu: false },
  { value: 'IN', label: 'India', flag: 'circle-flags:in', eu: false },
  { value: 'RU', label: 'Russia', flag: 'circle-flags:ru', eu: false },
  { value: 'BR', label: 'Brazil', flag: 'circle-flags:br', eu: false },
  { value: 'MX', label: 'Mexico', flag: 'circle-flags:mx', eu: false },
]

export const INVOICE_LANGUAGES = [
  { value: 'it', label: 'Italiano' },
  { value: 'en', label: 'English' },
  { value: 'de', label: 'Deutsch' },
  { value: 'fr', label: 'Fran\u00e7ais' },
]
